on: [push, pull_request]
name: Test
jobs:

  test-gopath:
    strategy:
      matrix:
        go-version: [1.13.x]
        # platform: [ubuntu-latest, windows-latest]
        platform: [ubuntu-latest]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: print
      run: pwd; echo $GOPATH; echo $GITHUB_WORKSPACE;
    - name: Test
      run: go env; go list ./...; go test ./...
